### ISSUE TITLE
Emoji with :name: don't show correctly in the Label overview

### ISSUE THREAD

**Issue by jfversluis** [Eilon/IssueLabelerEdgeExtension#1]
Not the end of the world of course, but thought I'd report it

![image](https://user-images.githubusercontent.com/939291/162942475-022a901c-0b13-4acc-873b-62e65a6a543c.png)

**Comment by Eilon** [comment]
Thanks! In GitHub I think some "legacy" emoji's use GitHub MarkDown Emoji syntax. In the past I've just written some code to clean them up and replace with Unicode emoji. Will do the same here!

**Comment by Eilon** [comment]
Better?

<img width="249" alt="image" src="https://user-images.githubusercontent.com/202643/163002835-0d11b7fd-6fb5-4dd1-abfd-72ea45431512.png">

**Comment by Eilon** [comment]
Issue is fixed. I'm re-submitting to the Extension Gallery, but if you fetch this repo and update your local extension you'll get the fix (instructions in the readme).

**Comment by jfversluis** [comment]
Yeah I got the local setup! Thanks for fixing it, I can now sleep peacefully.
